### ISSUE TITLE
Constuctor error

### ISSUE THREAD

**Issue by Yivan** [basilicom/pimcore-plugin-computer-vision#4]
A parameter is missing when creating a new ComputerVision Manager object.

```
<br />
<b>Warning</b>:  Missing argument 3 for ComputerVision\Manager::__construct(), called in C:\sql_dump
\pimcore.test1\www\plugins\ComputerVision\controllers\AdminController.php on line 22 and defined in 
<b>C:\sql_dump\pimcore.test1\www\plugins\ComputerVision\lib\ComputerVision\Manager.php</b> on line <b
>27</b><br />
```

In https://github.com/basilicom/pimcore-plugin-computer-vision/blob/master/lib/ComputerVision/Manager.php#L27,
`public function __construct($assetId, $type, $delay)`
should be changed by:
`public function __construct($assetId, $type, $delay = 0)`

as it is called from here https://github.com/basilicom/pimcore-plugin-computer-vision/blob/master/controllers/AdminController.php#L22 with just 2 parameters.

Thanks.

**Comment by monaBinder** [comment]
Done
