### ISSUE TITLE
Previous metadatas are deleted

### ISSUE THREAD

**Issue by Yivan** [basilicom/pimcore-plugin-computer-vision#6]
It seems previous metadatas are not preserved.
I filled an alt for an asset, and after running Computer Vision on it, my alt metadata was lost.

I think the plugin should append the Computer Vision tag to the existing non-computervision ones, so it is not destructive.
Actually user can lost their existing metadata if they use the plugin.

**Comment by christophluehr** [comment]
True. At least the documentation shall be improved and clearly state what the plugin is doing.
The envisioned use-case was just tagging new assets only.
As an enhancement, a switch (add or replace mode) would be beneficial

**Comment by monaBinder** [comment]
This plugin does not override existing metadata, but as long as the asset tab reloads to display the Computer Vision metadata, unsaved changes are lost. Thanks for the hint - I added a note in the documentation.

**Comment by Yivan** [comment]
Yes you are right, i confirm it is keeped if saved. Thanks for your return!
